version = 1
SPDX-PackageName = "rapid-rusty"
SPDX-PackageSupplier = "Florian Weßel <florianwessel@gmx.net>"
SPDX-PackageDownloadLocation = "https://github.com/mFlorianW/rapid-rusty"

[[annotations]]
path = [
    "REUSE.toml",
    ".gitignore",
    "**.json",
    "**.md",
    ".github/**",
    ".pre-commit-config.yaml",
    ".cz.toml",
    ".changelog.md.j2",
    "**/.csv",
    "**/CMakeLists.txt",
    ".clang-format",
    ".clang-tidy",
    "**/*.cmake",
    "configuration/android/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 All contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = [
    "rapid_android/RapidAndroid/img/*.svg",
    "rapid_android/RapidLaptimer/img/*.svg"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "CC-BY-1.0"
