// SPDX-FileCopyrightText: 2026 All contributors
//
// SPDX-License-Identifier: GPL-2.0-or-later

#ifndef RAPIDANDROID_RAPIDLIVESESSION_LOGGINGCATEGORIES_HPP
#define RAPIDANDROID_RAPIDLIVESESSION_LOGGINGCATEGORIES_HPP

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(rljd)
Q_DECLARE_LOGGING_CATEGORY(rlje)

#endif // RAPIDANDROID_RAPIDLIVESESSION_LOGGINGCATEGORIES_HPP
