// SPDX-FileCopyrightText: 2025 All contributors
//
// SPDX-License-Identifier: GPL-2.0-or-later

#ifndef RAPIDANDROID_WORKFLOW_LOGGINGCATEGORIES
#define RAPIDANDROID_WORKFLOW_LOGGINGCATEGORIES

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(devicemanagement)
Q_DECLARE_LOGGING_CATEGORY(dsm)

#endif // RAPIDANDROID_WORKFLOW_LOGGINGCATEGORIES
