# SPDX-FileCopyrightText: 2025 Florian Weßel <florianwessel@gmx.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later
name: Build CI Android

on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        abi: [android_x86_64, android_arm64_v8a]
        qt: [6.8.3, 6.10.1]
        include:
          - abi: android_x86_64
            preset: android-x86
          - abi: android_arm64_v8a
            preset: android-arm64
    name: Build_Android_${{ matrix.qt }}_${{ matrix.abi }}
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Install Android Setup
      uses: ./.github/actions/linux-install-qt-android

    - name: Build
      run: |
        echo "###############################################################"
        echo "# Start Build for Android ${{ matrix.abi }}"
        echo "###############################################################"
        export QT_ANDROID_ROOT=/home/runner/work/rapid-android/Qt/${{ matrix.qt }}/${{ matrix.abi }}
        export QT_HOST_PATH=/home/runner/work/rapid-android/Qt/${{ matrix.qt }}/gcc_64
        export PATH=${ANDROID_SDK_ROOT}/cmake/3.31.1/bin:${ANDROID_ROOT_PATH}/ndk/26.3.11579264:${PATH}
        git checkout ${{ matrix.commits }}
        cmake --preset ${{ matrix.preset }}
        cmake --build --preset ${{ matrix.preset }} --target apk --parallel
        echo "###############################################################"
        echo "# Finished Build Commit ${{ matrix.commits }}"
        echo "###############################################################"

    - name: Upload Artifact
      if: ${{ matrix.abi  }} == 'android_arm64_v8a' && ${{ matrix.qt }} == '6.10.1'
      uses: actions/upload-artifact@v4
      with:
        name: rapid-android_${{ github.run_id }}.apk
        path: build/android-arm64/rapid_android/android-build/rapid_android.apk
