# SPDX-FileCopyrightText: 2025 All contributors
#
# SPDX-License-Identifier: GPL-2.0-or-later
name: Pullrequest Build And Test

on:
  workflow_call:

jobs:
  Build_Desktop:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [Clang, GCC]
        qt: [6.8.3, 6.10.1]
        include:
          - compiler: GCC
            cxx: g++
            cc: gcc
          - compiler: Clang
            cxx: clang++
            cc: clang
    permissions:
      checks: write
      pull-requests: write
    name: Desktop_${{ matrix.qt }}-${{ matrix.compiler }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Install Qt
      uses: ./.github/actions/linux-install-qt
    - name: Install Dependencies
      uses: ./.github/actions/linux-install-dep
    - name: Setup default compiler
      run: |
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/${{ matrix.cc }} 100
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/${{ matrix.cxx }} 100
        echo "###############################################################"
        echo "Compiler CC"
        echo "$(cc --version)"
        echo "###############################################################"
        echo "###############################################################"
        echo "Compiler CXX"
        echo "$(c++ --version)"
        echo "###############################################################"
    - name: Create Test report directory
      run: mkdir -p ${PWD}/reports
    - name: Build and Test
      run: |
        for commit in $(git rev-list --reverse origin/${{ github.base_ref }}..origin/${{ github.head_ref }}); do

          echo "###############################################################"
          echo "# Start Build for Commit ${commit} for Desktop ${{ matrix.qt }}-${{ matrix.compiler }}"
          echo "###############################################################"
          git checkout ${commit}
          cmake --preset debug -DENABLE_WARNING_AS_ERROR=ON
          cmake --build --preset debug --target all --parallel
          echo "###############################################################"
          echo "# Finished Build Commit ${commit} for Desktop ${{ matrix.qt }}-${{ matrix.compiler }}"
          echo "###############################################################"

          echo "###############################################################"
          echo "# Start Tests for Commit ${commit} for Desktop ${{ matrix.qt }}-${{ matrix.compiler }}"
          echo "###############################################################"
          ctest --preset debug --parallel --output-on-failure --output-junit ${PWD}/reports/test-results_Desktop_${{ matrix.qt }}-${{ matrix.compiler }}-${commit}.xml
          echo "###############################################################"
          echo "# Finished Tests Commit ${commit} for Desktop ${{ matrix.qt }}-${{ matrix.compiler }}"
          echo "###############################################################"

        done
      env:
        QT_QPA_PLATFORM: offscreen
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: |
          reports/*.xml
        comment_mode: "failures"
    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Test Results Desktop ${{ matrix.qt }}-${{ matrix.compiler }}
        path: reports/*.xml
