# SPDX-FileCopyrightText: 2025 All contributors
#
# SPDX-License-Identifier: GPL-2.0-or-later
name: Pullrequest Build And Test

on:
  workflow_call:

jobs:
  Generate_Build_Jobs:
    runs-on: ubuntu-24.04
    outputs:
      commits: ${{ steps.commits.outputs.commits_json }}
    steps:
      - name: Install jq
        run: sudo apt-get install jq
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Commits list
        id: commits
        run: |
          commits=($(git rev-list --reverse origin/${{ github.base_ref }}..origin/${{ github.head_ref }}))
          commits=$(jq -n -c '$ARGS.positional' --args "${commits[@]}")
          echo "${commits[@]}"
          echo "commits_json=${commits[@]}" >> "$GITHUB_OUTPUT"

  Build:
    runs-on: ubuntu-24.04
    needs: [Generate_Build_Jobs]
    strategy:
      fail-fast: false
      matrix:
        commits: ${{ fromJson(needs.Generate_Build_Jobs.outputs.commits) }}
        compiler: [Clang, GCC]
        include:
          - compiler: GCC
            cxx: g++
            cc: gcc
          - compiler: Clang
            cxx: clang++
            cc: clang
    name: ${{matrix.compiler}}-${{matrix.commits}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Install Qt
      uses: ./.github/actions/linux-install-qt
    - name: Install Dependencies
      uses: ./.github/actions/linux-install-dep
    - name: Setup default compiler
      run: |
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/${{ matrix.cc }} 100
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/${{ matrix.cxx }} 100
        echo "###############################################################"
        echo "Compiler CC"
        echo "$(cc --version)"
        echo "###############################################################"
        echo "###############################################################"
        echo "Compiler CXX"
        echo "$(c++ --version)"
        echo "###############################################################"
    - name: Build
      run: |
        echo "###############################################################"
        echo "# Start Build Commit ${{ matrix.commits }}"
        echo "###############################################################"
        git checkout ${{ matrix.commits }}
        cmake --preset debug -DENABLE_WARNING_AS_ERROR=ON
        cmake --build --preset debug --target all --parallel
        echo "###############################################################"
        echo "# Finished Build Commit ${{ matrix.commits }}"
        echo "###############################################################"
      env:
        QT_QPA_PLATFORM: offscreen
    - name: Test
      id: tests
      run: |
        echo "###############################################################"
        echo "# Start Tests Commit ${{ matrix.commits }}"
        echo "###############################################################"
        ctest --preset debug --output-on-failure --output-junit test_results.xml
        echo "###############################################################"
        echo "# Finished Tests Commit ${{ matrix.commits }}"
        echo "###############################################################"
      env:
        QT_QPA_PLATFORM: offscreen
    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results@${{ matrix.compiler }}@${{ matrix.commits }}.xml
        path: build/debug/test_results.xml
