name: Include What You Use

on:
  workflow_call:

jobs:
  IWYU:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Install Dependencies
      uses: ./.github/actions/linux-install-dep

    - name: Install Qt
      uses: ./.github/actions/linux-install-qt

    - name: Install Include What You Use
      run: |
        sudo apt-get install iwyu

    - name: Setup clang as default compiler
      run: |
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100

    - name: Generate Compilation Database
      run: |
        cmake --preset debug
        cmake --build --preset debug

    - name: Run Include What You Use
      run: |
        iwyu_tool -p build/debug -o clang 2>&1 | tee iwyu_output.txt

    - name: Comment IWYU results
      if: always()
      uses: JacobDomagala/CompileResult@master
      with:
        comment_title: Include What You Result
        compile_result_file: iwyu_output.txt
