# SPDX-FileCopyrightText: 2025 All contributors
#
# SPDX-License-Identifier: GPL-2.0-or-later
name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'common/**'
      - 'rapid_android/**'
      - 'testhelper/**'
      - 'workflow/**'

permissions:
   pull-requests: write
   checks: write

jobs:
  Build_Desktop:
    uses: ./.github/workflows/pr-build.yml

  Build_Desktop_Status_Check:
    runs-on: ubuntu-latest
    needs: [Build_Desktop]
    if: always()
    steps:
      - name: Check Desktop Build Status
        run: |
          if [ "${{ needs.Build_Desktop.result }}" != "success" ]; then
            echo "Desktop builds failed"
            exit 1
          fi

  Build_Android:
    uses: ./.github/workflows/pr-build-android.yml

  Build_Android_Status_Check:
    runs-on:  ubuntu-latest
    needs: [Build_Android]
    if:  always()
    steps:
      - name: Check Android Build Status
        run: |
          if [ "${{ needs.Build_Android. result }}" != "success" ]; then
            echo "Android builds failed"
            exit 1
          fi

  # Linting_Include_What_You_Use:
  #   uses: ./.github/workflows/pr-iwyu.yml

  Linting_Clang_Tidy:
    uses: ./.github/workflows/pr-lint.yml

  Linting_Clazy:
    uses: ./.github/workflows/pr-clazy.yml
